function getListOfThings() {
  let list = new Array();
  list.push(['Jenga', 'Monopoly', 'Risk', 'Careers']);
  list.push(['Arizona', 'California', 'Massachusetts', 'New York']);
  list.push(['Poker', 'Go Fish', 'Bridge', 'Solitaire']);
  list.push(['Saskatchewan', 'British Columbia', 'Manitoba', 'Ontario']);
  list.push(['Boggle', 'Yahtzee', 'Backgammon', 'Dual']);
  list.push(['Cambodia', 'Denmark', 'Turkey', 'Jamaica']);
  list.push(['Musical Chairs', 'Pinata', 'Limbo', 'Charades']);
  list.push(['Middle Earth', 'Narnia', 'Hyrule', 'Wonderland']);
  list.push(['Archery', 'Ax Throwing', 'Fencing', 'Kendo']);
  list.push(['Doctor', 'Teacher', 'Dentist', 'Engineer']);
  list.push(['Karate', 'Taekwondo', 'Jujutsu', 'Judo']);
  list.push(['Sciences', 'Arts', 'Engineering', 'Management']);
  list.push(['Java', 'C++', 'Python', 'JavaScript']);
  list.push(['Cornell', 'Harvard', 'Yale', 'Princeton']);
  list.push(['MIT', 'Stanford', 'Berkeley', 'Georgia']);
  list.push(['Linux', 'Macintosh', 'Microsoft', 'DOS']);
  list.push(['Atari', 'Nintendo', 'Sega', 'Sony']);
  list.push(['Canoeing', 'Kayaking', 'Rafting', 'Rowing']);
  list.push(['Dog', 'Rabbit', 'Hamster', 'Cat']);
  list.push(['Mario', 'Zelda', 'Kirby', 'Sonic']);
  list.push(['Skiing', 'Skating', 'Snowboarding', 'Sledding']);
  list.push(['Airplane', 'Drone', 'Helicopter', 'Flying Car']);
  list.push(['Alligator', 'Lizard', 'Turtle', 'Chameleon']);
  list.push(['Basketball', 'Football', 'Handball', 'Lacrosse']);
  list.push(['Rinkball', 'Roller Derby', 'Ice Hockey', 'Speed Skating']);
  list.push(['Bear', 'Lion', 'Tiger', 'Coyote']);
  list.push(['Air Hockey', 'Connect Four', 'Dominoes', 'Ping Pong']);
  list.push(['Drag Racing', 'Autocross', 'Drifting', 'Street Racing']);
  list.push(['Chess', 'Backgammon', 'Checkers', 'Go']);
  list.push(['Left', 'Right', 'Up', 'Down']);
  list.push(['Cross Country', 'Pole Vault', 'Discus', 'Racewalking']);
  list.push(['Merlot', 'Shiraz', 'Chardonnay', 'Cabernet']);
  list.push(['Saturn', 'Venus', 'Jupiter', 'Mercury']);
  list.push(['France', 'England', 'Spain', 'Germany']);
  list.push(['Pecan', 'Walnut', 'Almond', 'Pistachio']);
  list.push(['Sapphire', 'Topaz', 'Pearl', 'Emerald']);
  list.push(['Minotaur', 'Sasquatch', 'Ogopogo', 'Bigfoot']);
  list.push(['Safflower', 'Canola', 'Olive', 'Sesame']);
  list.push(['Igneous', 'Basalt', 'Obsidian', 'Granite']);
  list.push(['Alternative', 'Blues', 'Rock', 'Classical']);
  list.push(['Sedan', 'Coupe', 'Compact', 'Convertible']);
  list.push(['Sarah', 'Amy', 'Kelly', 'Olivia']);
  list.push(['Brett', 'David', 'Joseph', 'Zane']);
  list.push(['Hermoine', 'Harry', 'Ginny', 'Ron']);
  list.push(['Draco', 'Scorpius', 'Bellatrix', 'Severus']);
  list.push(['Hufflepuff', 'Slytherin', 'Gryffindor', 'Ravenclaw']);
  list.push(['Gandalf', 'Frodo', 'Samwise', 'Legolas']);
  list.push(['Sauron', 'Gollum', 'Saruman', 'Shelob']);
  list.push(['Salt', 'Cinnamon', 'Paprika', 'Pepper']);
  list.push(['Beer', 'Cider', 'Wine', 'Rum']);
  list.push(['Pineapple', 'Banana', 'Apple', 'Plum']);
  list.push(['Carbon', 'Oxygen', 'Nitrogen', 'Helium']);
  list.push(['Rain Forest', 'Grassland', 'Desert', 'Tundra']);
  list.push(['Heart', 'Lungs', 'Brain', 'Kidneys']);
  list.push(['Blue', 'Red', 'Yellow', 'Green']);
  list.push(['Hail', 'Snow', 'Rain', 'Sleet']);
  list.push(['Stratus', 'Cirrus', 'Cumulus', 'Stratocumulus']);
  list.push(['West', 'East', 'South', 'North']);
  list.push(['Angry', 'Happy', 'Afraid', 'Sad']);
  list.push(['Macaroni', 'Lasagne', 'Spaghetti', 'Ravioli']);
  list.push(['Sweater', 'Pants', 'Shirt', 'Socks']);
  list.push(['Cute', 'Ugly', 'Fancy', 'Beautiful']);
  list.push(['Chicken', 'Goat', 'Cow', 'Horse']);
  list.push(['Wheat', 'Barley', 'Oat', 'Maize']);
  list.push(['Reading', 'Running', 'Knitting', 'Gaming']);
  list.push(['Golden Retriever', 'Pomeranian', 'German Shepherd', 'Samoyed']);
  list.push(['Carp', 'Guppy', 'Catfish', 'Goldfish']);
  list.push(['Cylinder', 'Cube', 'Pyramid', 'Sphere']);
  list.push(['Mystery', 'Fantasy', 'Romance', 'Thriller']);
  list.push(['Ocean', 'Lake', 'Sea', 'River']);
  list.push(['Grandma', 'Father', 'Sister', 'Uncle']);
  list.push(['Lipstick', 'Mascara', 'Eye Liner', 'Blush']);

  return list;
}